//update-dea.dto
export class UpdateDeaDto{
    DEA_NOMBRECOMPLETO?:string
    DEA_DOCIDENTIFICACION?:string
    DEA_CANTIDAD?:number
    DEA_NOMBREUBICACION?:string
    DEA_DIRECCIONUBICACION?:string
    DEA_CODIGOPOSTAL?:string
    DEA_CIUDADMUNICIPIO?:string
    DEA_DEPARTAMENTO?:string
    DEA_TIPOINSTALACION?:string
    DEA_TIPODECLARACION?:string
    DEA_TIPOESPACIO?:string
    DEA_NUMSERIE?:string
    DEA_MODELO?:string
    DEA_MARCA?:string
    DEA_IMPORTADORDISTRIBUIDOR?:string
    DEA_DESCLUGARUBICACION?:string
    DEA_GPS?:string
    DEA_FECHAREGISTRO?:Date
}